openapi: '3.0.0'
info:
  title: Student API
  version: '1.0.0'
servers:
  - url: http://STD22082.com
paths:
  /students:
    get:
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Server error
          content:
            text/plain:
              schema:
                type: string
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Server error
          content:
            text/plain:
              schema:
                type: string
  /students/{id}:
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Server error
          content:
            text/plain:
              schema:
                type: string
    put:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '500':
          description: Server error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
        class:
          type: string
      example:
        id: STD22082
        name: RANDRIANIMANANA Toavina Maria
        age: 17
        class: H3

